"""migrate_to_custom_rbac_auth

Revision ID: fa41af563911
Revises: 5c4f029fba4a
Create Date: 2026-07-19 22:51:46.796508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa41af563911'
down_revision: Union[str, Sequence[str], None] = '5c4f029fba4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Drop old tables referencing users.firebase_uid
    op.drop_table('files')
    op.drop_table('role_assignments')

    # 2. Modify users table structure
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.add_column('users', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default=''))
    op.create_primary_key('users_pkey', 'users', ['id'])
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')

    # 3. Modify roles table structure
    op.add_column('roles', sa.Column('can_upload', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_download', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_delete', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_share', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_manage_users', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('roles', 'description')

    # 4. Create new tables
    op.create_table('pool_usage',
    sa.Column('backend', sa.String(length=50), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('backend')
    )
    op.create_table('storage_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=True),
    sa.Column('backend_key', sa.String(length=255), nullable=True),
    sa.Column('trashed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('starred', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quotas',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('role_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['storage_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'id')
    op.add_column('roles', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('roles', 'can_manage_users')
    op.drop_column('roles', 'can_share')
    op.drop_column('roles', 'can_delete')
    op.drop_column('roles', 'can_download')
    op.drop_column('roles', 'can_upload')
    op.create_table('role_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_assignments_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.firebase_uid'], name=op.f('role_assignments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('role_assignments_pkey'))
    )
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.firebase_uid'], name=op.f('files_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey'))
    )
    op.drop_table('role_bindings')
    op.drop_table('user_quotas')
    op.drop_table('storage_nodes')
    op.drop_table('pool_usage')
    # ### end Alembic commands ###
